name: Update Adlist

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 8 * * 4' # 3 AM Detroit time in UTC


jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x ./adlist/combine_adlists.sh

      - name: Run Adlist Script
        run: ./adlist/combine_adlists.sh

      - name: Commit and Push Changes
        run: |
          git config --local user.name "jershbytes"
          git config --local user.email "jershbytes@users.noreply.github.com"
          git add ./adlist/duck_list.txt
          git commit -m "Update combined adlist [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push

          