name: Update Adlist

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x ./adlist/combine_adlists.sh

      - name: Run Adlist Script
        run: ./adlist/combine_adlists.sh

      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add ./adlist/duck_list.txt
          git commit -m "Update combined adlist [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
